apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yyq4jazs9-nodejs 
  janus-idp.io/tekton: yyq4jazs9-nodejs
  backstage.io/kubernetes-id: yyq4jazs9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yyq4jazs9-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml